name: SING_QUAL_EN
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - anyio=3.3.0
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=3.0.4
  - click=8.0.1
  - coverage=5.5
  - cryptography=3.4.7
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cython=0.29.23
  - dbus=1.13.18
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gh=1.14.0
  - git-lfs=2.13.3
  - glib=2.68.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.30.1
  - google-auth-oauthlib=0.4.1
  - grpcio=1.36.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipympl=0.7.0
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.17.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9b
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.7.1
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyter_server=1.10.1
  - jupyterlab=3.1.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.6.1
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libiconv=1.15
  - libidn2=2.3.1
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.10
  - libxslt=1.1.34
  - lxml=4.6.3
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - multidict=5.1.0
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclassic=0.3.1
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - nettle=3.7.2
  - ninja=1.10.2
  - notebook=6.4.0
  - numpy=1.20.2
  - numpy-base=1.20.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1l
  - packaging=20.9
  - pandas=1.2.5
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - protobuf=3.14.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.9.0
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.8.1
  - pytz=2021.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - requests-unixsocket=0.2.0
  - rsa=4.7.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.35.4
  - tensorboard=2.5.0
  - tensorboard-plugin-wit=1.6.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.10
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - appdirs==1.4.4
    - audioread==2.1.9
    - colorful==0.5.4
    - future==0.18.2
    - jupyter-contrib-core==0.3.3
    - librosa==0.8.1
    - llvmlite==0.36.0
    - mir-eval==0.6
    - numba==0.53.1
    - pesq==0.0.3
    - pooch==1.3.0
    - pypesq==1.2.4
    - pystoi==0.3.3
    - pyyaml==5.4.1
    - resampy==0.2.2
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn==0.11.2
    - soundfile==0.10.3.post1
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - torch-complex==0.2.1
    - tqdm==4.61.0
